### ISSUE TITLE
Need to fix Django "requires" for Fedora 28+

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-packaging#31]
https://github.com/pulp/pulp-packaging/blob/master/packages/pulp/pulp.spec#L414

```python-django``` has been removed from Fedora 28 and replaced with ```python2-django1.11``` since Django 1.11 is the last and only supported Django release w/ Python 2 support.

Pulp got mentioned in the planning document but I'm not sure they ever got up with us.

https://fedoraproject.org/wiki/Changes/Django20

>The new python2-django1.11 package will obsolete python2-django < 2 and python-django < 2, but it will deliberately not provide either of those. This will render packages depending on python(2)-django FTBFS (or broken runtime dependencies if they don't require Django at buildtime). This is intentional. If we don't do that, all Django packages in Fedora will just keep dragging the Legacy Python dependency chain forever. Package owners of Django applications requiring Python 2 will need to manually adjust their dependencies to use python2-django1.11 or move to Python 3 only (this is preferred but not always possible).

**Comment by dralley** [comment]
@pcreech

**Comment by asmacdo** [comment]
Related dev environment changes https://github.com/pulp/devel/pull/164

**Comment by pcreech** [comment]
This hasn't fallen off my radar.  We are currently trying to provide the ability to build fedora 28 rpms in our koji insance, but requires an update to mock/koji.

The updates are currently in the process of being planned.

**Comment by pcreech** [comment]
https://github.com/pulp/pulp-packaging/pull/52

Closing, as this fix has been merged, and we have successful testing on F28
